clause1(type(SystemUnitClass,Class),true).
clause1(type(RoleClassLib,Class),true).
clause1(type(Project,Class),true).
clause1(type(eClassConnection,Class),true).
clause1(type(PPRConnector,Class),true).
clause1(type(InstanceHierarchy,Class),true).
clause1(type(RoleRequirements,Class),true).
clause1(type(ExternalInterface,Class),true).
clause1(type(ExternalReference,Class),true).
clause1(type(SystemUnitClassLib,Class),true).
clause1(type(RoleClass,Class),true).
clause1(type(BaseInterface,Class),true).
clause1(type(InternalElement,Class),true).
clause1(type(ChangeMode,Class),true).
clause1(type(CAEXFile,Class),true).
clause1(type(SupportedRoleClass,Class),true).
clause1(type(AdditionalInformation,Class),true).
clause1(type(PortConnector,Class),true).
clause1(type(InterfaceClass,Class),true).
clause1(type(CAEXBasicObject,Class),true).
clause1(type(InterfaceClassLib,Class),true).
clause1(type(Order,Class),true).
clause1(type(InternalLink,Class),true).
clause1(type(Attribute,Class),true).
clause1(type(Unit_of_measure,Class),true).

