:-dynamic(hasExternalInterface/2).
:-dynamic(IEPartOf/2).
:-dynamic(hasInterfaceClass/2).
:-dynamic(unitExternalInterface/2).
:-dynamic(hasRoleRequeriment/2).
:-dynamic(hasInterfaceClassLib/2).
:-dynamic(eClassIsConnectedTo/2).
:-dynamic(supportedRoleClass/2).
:-dynamic(hasAttribute/2).
:-dynamic(SystemUnitClassPartOf/2).
:-dynamic(hasRoleClassLib/2).
:-dynamic(InterfaceClassAttribute/2).
:-dynamic(hasChangeMode/2).
:-dynamic(hasInternalElement/2).
:-dynamic(hasSystemUnitClassLib/2).
:-dynamic(hasRoleClass/2).
:-dynamic(hasUnit/2).
:-dynamic(hasSystemUnitClass/2).
:-dynamic(refBaseRoleClassPath/2).
:-dynamic(hasInstanceHierarchy/2).
:-dynamic(hasProject/2).
:-dynamic(roleClassRefSem/2).
:-dynamic(interfaceClassIsPartOf/2).
:-dynamic(hasAdditionalInformation/2).
:-dynamic(hasExternalReference/2).
:-dynamic(hasSchemaVersion/2).
:-dynamic(hasProjectTitle/2).
:-dynamic(externalReferenceAlias/2).
:-dynamic(hasDataType/2).
:-dynamic(hasVersion/2).
:-dynamic(InterfaceClassName/2).
:-dynamic(hasWriterVendorURL/2).
:-dynamic(externalInterfaceName/2).
:-dynamic(InterfaceClassAttribute/2).
:-dynamic(classificationClass/2).
:-dynamic(externalReferencePath/2).
:-dynamic(RefBaseSystemUnitPath/2).
:-dynamic(Direction/2).
:-dynamic(hasAttributeName/2).
:-dynamic(eClassVersion/2).
:-dynamic(hasWriterVendor/2).
:-dynamic(externalInterfaceId/2).
:-dynamic(internalElementId/2).
:-dynamic(lastWritingDate/2).
:-dynamic(name/2).
:-dynamic(refBaseClassPath/2).
:-dynamic(hasWriterVersion/2).
:-dynamic(refBaseRoleClassPath/2).
:-dynamic(hasWriterId/2).
:-dynamic(hasFileName/2).
:-dynamic(title/2).
:-dynamic(hasWriterRelease/2).
:-dynamic(refRoleClassPath/2).
:-dynamic(interfaceClassIsPartOf/2).
:-dynamic(internalElementName/2).
:-dynamic(hasValue/2).
:-dynamic(eClassIRDI/2).
:-dynamic(hasAutomationMLVersion/2).
:-dynamic(SystemUnitClassName/2).
:-dynamic(hasProjectId/2).
:-dynamic(identifier/2).
:-dynamic(roleClassName/2).
:-dynamic(hasWriterName/2).

clause1(type(hasExternalInterface,ObjectProperty),true).
clause1(type(IEPartOf,ObjectProperty),true).
clause1(type(hasInterfaceClass,ObjectProperty),true).
clause1(type(unitExternalInterface,ObjectProperty),true).
clause1(type(hasRoleRequeriment,ObjectProperty),true).
clause1(type(hasInterfaceClassLib,ObjectProperty),true).
clause1(type(eClassIsConnectedTo,ObjectProperty),true).
clause1(type(supportedRoleClass,ObjectProperty),true).
clause1(type(hasAttribute,ObjectProperty),true).
clause1(type(SystemUnitClassPartOf,ObjectProperty),true).
clause1(type(hasRoleClassLib,ObjectProperty),true).
clause1(type(InterfaceClassAttribute,ObjectProperty),true).
clause1(type(hasChangeMode,ObjectProperty),true).
clause1(type(hasInternalElement,ObjectProperty),true).
clause1(type(hasSystemUnitClassLib,ObjectProperty),true).
clause1(type(hasRoleClass,ObjectProperty),true).
clause1(type(hasUnit,ObjectProperty),true).
clause1(type(hasSystemUnitClass,ObjectProperty),true).
clause1(type(refBaseRoleClassPath,ObjectProperty),true).
clause1(type(hasInstanceHierarchy,ObjectProperty),true).
clause1(type(hasProject,ObjectProperty),true).
clause1(type(roleClassRefSem,ObjectProperty),true).
clause1(type(interfaceClassIsPartOf,ObjectProperty),true).
clause1(type(hasAdditionalInformation,ObjectProperty),true).
clause1(type(hasExternalReference,ObjectProperty),true).
clause1(type(SystemUnitClass,Class),true).
clause1(type(RoleClassLib,Class),true).
clause1(type(Project,Class),true).
clause1(type(PPRConnector,Class),true).
clause1(type(InstanceHierarchy,Class),true).
clause1(type(RoleRequirements,Class),true).
clause1(type(ExternalInterface,Class),true).
clause1(type(ExternalReference,Class),true).
clause1(type(SystemUnitClassLib,Class),true).
clause1(type(RoleClass,Class),true).
clause1(type(BaseInterface,Class),true).
clause1(type(InternalElement,Class),true).
clause1(type(ChangeMode,Class),true).
clause1(type(CAEXFile,Class),true).
clause1(type(eClassSpecification,Class),true).
clause1(type(SupportedRoleClass,Class),true).
clause1(type(AdditionalInformation,Class),true).
clause1(type(PortConnector,Class),true).
clause1(type(InterfaceClass,Class),true).
clause1(type(CAEXBasicObject,Class),true).
clause1(type(InterfaceClassLib,Class),true).
clause1(type(Order,Class),true).
clause1(type(InternalLink,Class),true).
clause1(type(Attribute,Class),true).
clause1(type(Unit_of_measure,Class),true).
clause1(type(hasSchemaVersion,DatatypeProperty),true).
clause1(type(hasProjectTitle,DatatypeProperty),true).
clause1(type(externalReferenceAlias,DatatypeProperty),true).
clause1(type(hasDataType,DatatypeProperty),true).
clause1(type(hasVersion,DatatypeProperty),true).
clause1(type(InterfaceClassName,DatatypeProperty),true).
clause1(type(hasWriterVendorURL,DatatypeProperty),true).
clause1(type(externalInterfaceName,DatatypeProperty),true).
clause1(type(InterfaceClassAttribute,DatatypeProperty),true).
clause1(type(classificationClass,DatatypeProperty),true).
clause1(type(externalReferencePath,DatatypeProperty),true).
clause1(type(RefBaseSystemUnitPath,DatatypeProperty),true).
clause1(type(Direction,DatatypeProperty),true).
clause1(type(hasAttributeName,DatatypeProperty),true).
clause1(type(eClassVersion,DatatypeProperty),true).
clause1(type(hasWriterVendor,DatatypeProperty),true).
clause1(type(externalInterfaceId,DatatypeProperty),true).
clause1(type(internalElementId,DatatypeProperty),true).
clause1(type(lastWritingDate,DatatypeProperty),true).
clause1(type(name,DatatypeProperty),true).
clause1(type(refBaseClassPath,DatatypeProperty),true).
clause1(type(hasWriterVersion,DatatypeProperty),true).
clause1(type(refBaseRoleClassPath,DatatypeProperty),true).
clause1(type(hasWriterId,DatatypeProperty),true).
clause1(type(hasFileName,DatatypeProperty),true).
clause1(type(title,DatatypeProperty),true).
clause1(type(hasWriterRelease,DatatypeProperty),true).
clause1(type(refRoleClassPath,DatatypeProperty),true).
clause1(type(interfaceClassIsPartOf,DatatypeProperty),true).
clause1(type(internalElementName,DatatypeProperty),true).
clause1(type(hasValue,DatatypeProperty),true).
clause1(type(eClassIRDI,DatatypeProperty),true).
clause1(type(hasAutomationMLVersion,DatatypeProperty),true).
clause1(type(SystemUnitClassName,DatatypeProperty),true).
clause1(type(hasProjectId,DatatypeProperty),true).
clause1(type(identifier,DatatypeProperty),true).
clause1(type(roleClassName,DatatypeProperty),true).
clause1(type(hasWriterName,DatatypeProperty),true).

