:-dynamic(hasExternalInterface/2).
:-dynamic(hasInterfaceClass/2).
:-dynamic(unitExternalInterface/2).
:-dynamic(hasRoleRequeriment/2).
:-dynamic(hasInterfaceClassLib/2).
:-dynamic(eClassIsConnectedTo/2).
:-dynamic(iePartOf/2).
:-dynamic(supportedRoleClass/2).
:-dynamic(hasAttribute/2).
:-dynamic(hasRoleClassLib/2).
:-dynamic(systemUnitClassPartOf/2).
:-dynamic(hasChangeMode/2).
:-dynamic(hasInternalElement/2).
:-dynamic(hasSystemUnitClassLib/2).
:-dynamic(hasRoleClass/2).
:-dynamic(hasUnit/2).
:-dynamic(hasSystemUnitClass/2).
:-dynamic(interfaceClassAttribute/2).
:-dynamic(refBaseRoleClassPath/2).
:-dynamic(hasInstanceHierarchy/2).
:-dynamic(hasProject/2).
:-dynamic(roleClassRefSem/2).
:-dynamic(interfaceClassIsPartOf/2).
:-dynamic(hasAdditionalInformation/2).
:-dynamic(hasExternalReference/2).
:-dynamic(refSemantic/2).
:-dynamic(hasSchemaVersion/2).
:-dynamic(hasProjectTitle/2).
:-dynamic(externalReferenceAlias/2).
:-dynamic(hasDataType/2).
:-dynamic(hasVersion/2).
:-dynamic(hasWriterVendorURL/2).
:-dynamic(refBaseSystemUnitPath/2).
:-dynamic(externalInterfaceName/2).
:-dynamic(classificationClass/2).
:-dynamic(externalReferencePath/2).
:-dynamic(hasAttributeName/2).
:-dynamic(eClassVersion/2).
:-dynamic(hasWriterVendor/2).
:-dynamic(externalInterfaceId/2).
:-dynamic(internalElementId/2).
:-dynamic(lastWritingDate/2).
:-dynamic(name/2).
:-dynamic(refBaseClassPath/2).
:-dynamic(hasWriterVersion/2).
:-dynamic(direction/2).
:-dynamic(refBaseRoleClassPath/2).
:-dynamic(hasWriterId/2).
:-dynamic(interfaceClassName/2).
:-dynamic(systemUnitClassName/2).
:-dynamic(hasFileName/2).
:-dynamic(title/2).
:-dynamic(hasWriterRelease/2).
:-dynamic(refRoleClassPath/2).
:-dynamic(interfaceClassIsPartOf/2).
:-dynamic(internalElementName/2).
:-dynamic(hasValue/2).
:-dynamic(eClassIRDI/2).
:-dynamic(hasAutomationMLVersion/2).
:-dynamic(hasProjectId/2).
:-dynamic(interfaceClassAttribute/2).
:-dynamic(identifier/2).
:-dynamic(roleClassName/2).
:-dynamic(hasWriterName/2).

clause1(type(systemUnitClass,class),true).
clause1(type(roleClassLib,class),true).
clause1(type(project,class),true).
clause1(type(pPRConnector,class),true).
clause1(type(instanceHierarchy,class),true).
clause1(type(roleRequirements,class),true).
clause1(type(externalInterface,class),true).
clause1(type(externalReference,class),true).
clause1(type(systemUnitClassLib,class),true).
clause1(type(roleClass,class),true).
clause1(type(baseInterface,class),true).
clause1(type(internalElement,class),true).
clause1(type(changeMode,class),true).
clause1(type(cAEXFile,class),true).
clause1(type(eClassSpecification,class),true).
clause1(type(supportedRoleClass,class),true).
clause1(type(additionalInformation,class),true).
clause1(type(portConnector,class),true).
clause1(type(interfaceClass,class),true).
clause1(type(cAEXBasicObject,class),true).
clause1(type(interfaceClassLib,class),true).
clause1(type(order,class),true).
clause1(type(internalLink,class),true).
clause1(type(attribute,class),true).
clause1(type(unit_of_measure,class),true).
clause1(type(hasExternalInterface,objectproperty),true).
clause1(type(hasInterfaceClass,objectproperty),true).
clause1(type(unitExternalInterface,objectproperty),true).
clause1(type(hasRoleRequeriment,objectproperty),true).
clause1(type(hasInterfaceClassLib,objectproperty),true).
clause1(type(eClassIsConnectedTo,objectproperty),true).
clause1(type(iePartOf,objectproperty),true).
clause1(type(supportedRoleClass,objectproperty),true).
clause1(type(hasAttribute,objectproperty),true).
clause1(type(hasRoleClassLib,objectproperty),true).
clause1(type(systemUnitClassPartOf,objectproperty),true).
clause1(type(hasChangeMode,objectproperty),true).
clause1(type(hasInternalElement,objectproperty),true).
clause1(type(hasSystemUnitClassLib,objectproperty),true).
clause1(type(hasRoleClass,objectproperty),true).
clause1(type(hasUnit,objectproperty),true).
clause1(type(hasSystemUnitClass,objectproperty),true).
clause1(type(interfaceClassAttribute,objectproperty),true).
clause1(type(refBaseRoleClassPath,objectproperty),true).
clause1(type(hasInstanceHierarchy,objectproperty),true).
clause1(type(hasProject,objectproperty),true).
clause1(type(roleClassRefSem,objectproperty),true).
clause1(type(interfaceClassIsPartOf,objectproperty),true).
clause1(type(hasAdditionalInformation,objectproperty),true).
clause1(type(hasExternalReference,objectproperty),true).
clause1(type(refSemantic,datatypeproperty),true).
clause1(type(hasSchemaVersion,datatypeproperty),true).
clause1(type(hasProjectTitle,datatypeproperty),true).
clause1(type(externalReferenceAlias,datatypeproperty),true).
clause1(type(hasDataType,datatypeproperty),true).
clause1(type(hasVersion,datatypeproperty),true).
clause1(type(hasWriterVendorURL,datatypeproperty),true).
clause1(type(refBaseSystemUnitPath,datatypeproperty),true).
clause1(type(externalInterfaceName,datatypeproperty),true).
clause1(type(classificationClass,datatypeproperty),true).
clause1(type(externalReferencePath,datatypeproperty),true).
clause1(type(hasAttributeName,datatypeproperty),true).
clause1(type(eClassVersion,datatypeproperty),true).
clause1(type(hasWriterVendor,datatypeproperty),true).
clause1(type(externalInterfaceId,datatypeproperty),true).
clause1(type(internalElementId,datatypeproperty),true).
clause1(type(lastWritingDate,datatypeproperty),true).
clause1(type(name,datatypeproperty),true).
clause1(type(refBaseClassPath,datatypeproperty),true).
clause1(type(hasWriterVersion,datatypeproperty),true).
clause1(type(direction,datatypeproperty),true).
clause1(type(refBaseRoleClassPath,datatypeproperty),true).
clause1(type(hasWriterId,datatypeproperty),true).
clause1(type(interfaceClassName,datatypeproperty),true).
clause1(type(systemUnitClassName,datatypeproperty),true).
clause1(type(hasFileName,datatypeproperty),true).
clause1(type(title,datatypeproperty),true).
clause1(type(hasWriterRelease,datatypeproperty),true).
clause1(type(refRoleClassPath,datatypeproperty),true).
clause1(type(interfaceClassIsPartOf,datatypeproperty),true).
clause1(type(internalElementName,datatypeproperty),true).
clause1(type(hasValue,datatypeproperty),true).
clause1(type(eClassIRDI,datatypeproperty),true).
clause1(type(hasAutomationMLVersion,datatypeproperty),true).
clause1(type(hasProjectId,datatypeproperty),true).
clause1(type(interfaceClassAttribute,datatypeproperty),true).
clause1(type(identifier,datatypeproperty),true).
clause1(type(roleClassName,datatypeproperty),true).
clause1(type(hasWriterName,datatypeproperty),true).

