isTriple(ahasChangeMode,range,aChangeMode).
isTriple(ahasChangeMode,doman,aCAEXBasicObject).
isTriple(ahasChangeMode,type,aObjectProperty).
isTriple(aexternalReferenceAlias,range,astring).
isTriple(aexternalReferenceAlias,domain,aExternalReference).
isTriple(aexternalReferenceAlias,type,aDatatypeProperty).
isTriple(ahasProject,range,aProject).
isTriple(ahasProject,domain,aAdditionalInformation).
isTriple(ahasProject,type,aObjectProperty).
isTriple(aexternalInterfaceId,range,astring).
isTriple(aexternalInterfaceId,domain,aExternalInterface).
isTriple(aexternalInterfaceId,type,aFunctionalProperty).
isTriple(aexternalInterfaceId,type,aDatatypeProperty).
isTriple(ahasExternalInterface,range,aExternalInterface).
isTriple(ahasExternalInterface,domain,aInternalElement).
isTriple(ahasExternalInterface,type,aObjectProperty).
isTriple(ahasAdditionalInformation,range,aAdditionalInformation).
isTriple(ahasAdditionalInformation,domain,aCAEXFile).
isTriple(ahasAdditionalInformation,type,aObjectProperty).
isTriple(aProject,type,aClass).
isTriple(asupportedRoleClass,range,aSupportedRoleClass).
isTriple(asupportedRoleClass,domain,aInternalElement).
isTriple(asupportedRoleClass,domain,aSystemUnitClass).
isTriple(asupportedRoleClass,type,aObjectProperty).
isTriple(aSystemUnitClassName,range,astring).
isTriple(aSystemUnitClassName,domain,aSystemUnitClass).
isTriple(aSystemUnitClassName,type,aDatatypeProperty).
isTriple(aSystemUnitClassName,type,aFunctionalProperty).
isTriple(ahasAttributeName,range,astring).
isTriple(ahasAttributeName,domain,aAttribute).
isTriple(ahasAttributeName,type,aDatatypeProperty).
isTriple(aCAEXBasicObject,type,aClass).
isTriple(aAttribute,type,aClass).
isTriple(aInterfaceClassLib,type,aClass).
isTriple(ahasRoleRequeriment,range,aRoleRequirements).
isTriple(ahasRoleRequeriment,domain,aInternalElement).
isTriple(ahasRoleRequeriment,type,aObjectProperty).
isTriple(aexternalInterfaceName,range,astring).
isTriple(aexternalInterfaceName,domain,aExternalInterface).
isTriple(aexternalInterfaceName,type,aDatatypeProperty).
isTriple(aSystemUnitClass,type,aClass).
isTriple(aPortConnector,subClassOf,aInterfaceClass).
isTriple(aPortConnector,type,aClass).
isTriple(ahasSystemUnitClass,range,aSystemUnitClass).
isTriple(ahasSystemUnitClass,domain,aSystemUnitClassLib).
isTriple(ahasSystemUnitClass,type,aObjectProperty).
isTriple(ahasDataType,range,aanyURI).
isTriple(ahasDataType,domain,aAttribute).
isTriple(ahasDataType,type,aDatatypeProperty).
isTriple(ahasWriterVendor,range,astring).
isTriple(ahasWriterVendor,domain,aAdditionalInformation).
isTriple(ahasWriterVendor,type,aDatatypeProperty).
isTriple(aname,type,aDatatypeProperty).
isTriple(aname,type,aFunctionalProperty).
isTriple(ahasSystemUnitClassLib,range,aSystemUnitClassLib).
isTriple(ahasSystemUnitClassLib,domain,aCAEXFile).
isTriple(ahasSystemUnitClassLib,type,aObjectProperty).
isTriple(ahasExternalReference,range,aExternalReference).
isTriple(ahasExternalReference,domain,aCAEXFile).
isTriple(ahasExternalReference,type,aObjectProperty).
isTriple(aunitExternalInterface,range,aExternalInterface).
isTriple(aunitExternalInterface,domain,aSystemUnitClass).
isTriple(aunitExternalInterface,type,aObjectProperty).
isTriple(ainterfaceClassIsPartOf,range,aInterfaceClass).
isTriple(ainterfaceClassIsPartOf,domain,aInterfaceClass).
isTriple(ainterfaceClassIsPartOf,type,aDatatypeProperty).
isTriple(aExternalReference,type,aClass).
isTriple(ahasWriterName,range,astring).
isTriple(ahasWriterName,domain,aAdditionalInformation).
isTriple(ahasWriterName,type,aDatatypeProperty).
isTriple(aclassificationClass,range,astring).
isTriple(aclassificationClass,doman,aeClassConnection).
isTriple(aclassificationClass,type,aDatatypeProperty).
isTriple(aRoleClass,type,aClass).
isTriple(aeClassConnection,type,aClass).
isTriple(ahasAttribute,range,aAttribute).
isTriple(ahasAttribute,domain,aInternalElement).
isTriple(ahasAttribute,type,aObjectProperty).
isTriple(aExternalInterface,type,aClass).
isTriple(ahasWriterId,range,astring).
isTriple(ahasWriterId,domain,aAdditionalInformation).
isTriple(ahasWriterId,type,aFunctionalProperty).
isTriple(ahasWriterId,type,aDatatypeProperty).
isTriple(aInterfaceClass,type,aClass).
isTriple(aeClassVersion,range,astring).
isTriple(aeClassVersion,doman,aeClassConnection).
isTriple(aeClassVersion,type,aDatatypeProperty).
isTriple(ahasUnit,range,aUnit_of_measure).
isTriple(ahasUnit,domain,aAttribute).
isTriple(ahasUnit,type,aObjectProperty).
isTriple(arefBaseClassPath,range,astring).
isTriple(arefBaseClassPath,domain,aExternalInterface).
isTriple(arefBaseClassPath,domain,aInterfaceClass).
isTriple(arefBaseClassPath,domain,aRoleClassLib).
isTriple(arefBaseClassPath,type,aDatatypeProperty).
isTriple(aInterfaceClassName,range,astring).
isTriple(aInterfaceClassName,domain,aInterfaceClass).
isTriple(aInterfaceClassName,type,aDatatypeProperty).
isTriple(ainternalElementName,range,astring).
isTriple(ainternalElementName,domain,aInternalElement).
isTriple(ainternalElementName,type,aFunctionalProperty).
isTriple(ainternalElementName,type,aDatatypeProperty).
isTriple(ahasInstanceHierarchy,range,aInstanceHierarchy).
isTriple(ahasInstanceHierarchy,domain,aCAEXFile).
isTriple(ahasInstanceHierarchy,type,aObjectProperty).
isTriple(a,vocabulary,a).
isTriple(a,vocabulary,a).
isTriple(a,vocabulary,a).
isTriple(a,vocabulary,a).
isTriple(a,isDefinedBy,a).
isTriple(a,type,aOntology).
isTriple(a,vocabulary,a).
isTriple(a,license,a).
isTriple(a,vocabulary,anamespace).
isTriple(a,vocabulary,a).
isTriple(a,vocabulary,a).
isTriple(a,vocabulary,a).
isTriple(aeClassID,range,astring).
isTriple(aeClassID,doman,aeClassConnection).
isTriple(aeClassID,type,aDatatypeProperty).
isTriple(aeClassID,type,aFunctionalProperty).
isTriple(aRoleRequirements,type,aClass).
isTriple(aChangeMode,type,aClass).
isTriple(aRoleClassLib,type,aClass).
isTriple(arefBaseRoleClassPath,range,astring).
isTriple(arefBaseRoleClassPath,domain,aRoleRequirements).
isTriple(arefBaseRoleClassPath,type,aObjectProperty).
isTriple(aRefBaseSystemUnitPath,range,astring).
isTriple(aRefBaseSystemUnitPath,domain,aInternalElement).
isTriple(aRefBaseSystemUnitPath,type,aDatatypeProperty).
isTriple(arefRoleClassPath,range,astring).
isTriple(arefRoleClassPath,domain,aSupportedRoleClass).
isTriple(arefRoleClassPath,type,aDatatypeProperty).
isTriple(ahasRoleClass,range,aRoleClass).
isTriple(ahasRoleClass,domain,aRoleClassLib).
isTriple(ahasRoleClass,type,aObjectProperty).
isTriple(aroleClassName,range,astring).
isTriple(aroleClassName,domain,aRoleClass).
isTriple(aroleClassName,type,aDatatypeProperty).
isTriple(aroleClassName,type,aFunctionalProperty).
isTriple(aCAEXFile,type,aClass).
isTriple(ahasVersion,range,astring).
isTriple(ahasVersion,type,aDatatypeProperty).
isTriple(aAdditionalInformation,type,aClass).
isTriple(aSystemUnitClassPartOf,domain,aSystemUnitClass).
isTriple(aSystemUnitClassPartOf,type,aObjectProperty).
isTriple(ahasProjectId,subPropertyOf,aidentifier).
isTriple(ahasProjectId,subPropertyOf,atitle).
isTriple(ahasProjectId,range,astring).
isTriple(ahasProjectId,domain,aProject).
isTriple(ahasProjectId,type,aDatatypeProperty).
isTriple(ahasRoleClassLib,range,aRoleClassLib).
isTriple(ahasRoleClassLib,domain,aCAEXFile).
isTriple(ahasRoleClassLib,type,aObjectProperty).
isTriple(aexternalReferencePath,range,astring).
isTriple(aexternalReferencePath,domain,aExternalReference).
isTriple(aexternalReferencePath,type,aDatatypeProperty).
isTriple(aSystemUnitClassLib,type,aClass).
isTriple(ahasFileName,range,astring).
isTriple(ahasFileName,domain,aCAEXFile).
isTriple(ahasFileName,type,aDatatypeProperty).
isTriple(aeClassIsConnectedTo,type,aObjectProperty).
isTriple(ahasInterfaceClassLib,range,aInterfaceClassLib).
isTriple(ahasInterfaceClassLib,domain,aCAEXFile).
isTriple(ahasInterfaceClassLib,type,aObjectProperty).
isTriple(aIEPartOf,range,aInternalElement).
isTriple(aIEPartOf,domain,aInternalElement).
isTriple(aIEPartOf,type,aObjectProperty).
isTriple(aIEPartOf,type,aTransitiveProperty).
isTriple(aPPRConnector,subClassOf,aInterfaceClass).
isTriple(aPPRConnector,type,aClass).
isTriple(ahasSchemaVersion,range,astring).
isTriple(ahasSchemaVersion,domain,aCAEXFile).
isTriple(ahasSchemaVersion,type,aDatatypeProperty).
isTriple(ahasProjectTitle,subPropertyOf,atitle).
isTriple(ahasProjectTitle,range,astring).
isTriple(ahasProjectTitle,domain,aProject).
isTriple(ahasProjectTitle,type,aDatatypeProperty).
isTriple(alastWritingDate,range,adateTime).
isTriple(alastWritingDate,domain,aAdditionalInformation).
isTriple(alastWritingDate,type,aDatatypeProperty).
isTriple(aInterfaceClassAttribute,range,aAttribute).
isTriple(aInterfaceClassAttribute,domain,aInterfaceClass).
isTriple(aInterfaceClassAttribute,type,aDatatypeProperty).
isTriple(ahasWriterRelease,range,astring).
isTriple(ahasWriterRelease,domain,aAdditionalInformation).
isTriple(ahasWriterRelease,type,aDatatypeProperty).
isTriple(ahasWriterVersion,range,astring).
isTriple(ahasWriterVersion,domain,aAdditionalInformation).
isTriple(ahasWriterVersion,type,aDatatypeProperty).
isTriple(ahasWriterVendorURL,range,astring).
isTriple(ahasWriterVendorURL,domain,aAdditionalInformation).
isTriple(ahasWriterVendorURL,type,aDatatypeProperty).
isTriple(aDirection,range,astring).
isTriple(aDirection,domain,aOrder).
isTriple(aDirection,type,aDatatypeProperty).
isTriple(aOrder,subClassOf,aInterfaceClass).
isTriple(aOrder,type,aClass).
isTriple(aBaseInterface,subClassOf,aInterfaceClass).
isTriple(aBaseInterface,type,aClass).
isTriple(aSupportedRoleClass,type,aClass).
isTriple(aInstanceHierarchy,type,aClass).
isTriple(aInternalElement,type,aClass).
isTriple(aInternalLink,type,aClass).
isTriple(ahasValue,range,astring).
isTriple(ahasValue,domain,aAttribute).
isTriple(ahasValue,type,aDatatypeProperty).
isTriple(ahasInternalElement,range,aInternalElement).
isTriple(ahasInternalElement,domain,aInstanceHierarchy).
isTriple(ahasInternalElement,type,aObjectProperty).
isTriple(ahasAutomationMLVersion,range,astring).
isTriple(ahasAutomationMLVersion,domain,aAdditionalInformation).
isTriple(ahasAutomationMLVersion,type,aDatatypeProperty).
isTriple(ainternalElementId,range,astring).
isTriple(ainternalElementId,domain,aInternalElement).
isTriple(ainternalElementId,type,aFunctionalProperty).
isTriple(ainternalElementId,type,aDatatypeProperty).
isTriple(ahasInterfaceClass,range,aInterfaceClass).
isTriple(ahasInterfaceClass,domain,aInterfaceClassLib).
isTriple(ahasInterfaceClass,type,aObjectProperty).
